export interface Alpha {
	name: string,
	duration: string,
	website: string,
	discord: string,
	twitter: string,
	symbol: string,
	caller: string,
	date: string,
	floor_price: number,
	volume_24h: number,
	twitter_mentions: number,
	entry: number,
	exit: number,
	image: string,
	profile: string,
	project_details: string,
	description: string,
	risk_analysis: string,
	project_analysis: string,
	p_l: number,
	duration_date: string,
	call_FP: number,
	exit_FP: number,
}
